// frontend/src/pages/HomePage.jsx
import { Link } from 'react-router-dom';
import { Code2, Trophy, Zap, Users } from 'lucide-react';

const HomePage = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 via-white to-accent-50">
      {/* Hero Section */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-16 text-center">
        <Code2 className="h-16 w-16 text-primary-600 mx-auto mb-6" />
        <h1 className="text-5xl md:text-6xl font-extrabold text-gray-900 mb-6">
          Welcome to <span className="text-primary-600">Ascend</span>
        </h1>
        <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
          Real-time competitive programming platform with AI-generated problems,
          live matches, and global leaderboards.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Link to="/register" className="btn-primary text-lg px-8 py-3">
            Get Started
          </Link>
          <Link to="/login" className="btn-secondary text-lg px-8 py-3">
            Sign In
          </Link>
        </div>
      </div>

      {/* Features */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="grid md:grid-cols-3 gap-8">
          <div className="card text-center">
            <Zap className="h-12 w-12 text-primary-600 mx-auto mb-4" />
            <h3 className="text-xl font-bold mb-2">Real-Time Matches</h3>
            <p className="text-gray-600">
              Compete live with players worldwide in timed coding challenges
            </p>
          </div>
          <div className="card text-center">
            <Trophy className="h-12 w-12 text-accent-500 mx-auto mb-4" />
            <h3 className="text-xl font-bold mb-2">League System</h3>
            <p className="text-gray-600">
              Climb the ranks through Bronze to Master leagues
            </p>
          </div>
          <div className="card text-center">
            <Users className="h-12 w-12 text-primary-600 mx-auto mb-4" />
            <h3 className="text-xl font-bold mb-2">AI Problems</h3>
            <p className="text-gray-600">
              Fresh challenges generated by advanced AI
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HomePage;
